#!/bin/sh -e

# Copyright (c) 2020, Institute for Defense Analyses
# 4850 Mark Center Drive, Alexandria, VA 22311-1882; 703-845-2500
#
# All rights reserved.
#
# This file is part of the conveyor package. For license information,
# see the LICENSE file in the top level directory of the distribution.

export MPP_INIT_QUIET=1
if test -x ./histogupc; then
  $LAUNCH ./histogupc
else
  $LAUNCH ./histogram
fi
if test -x ./indexgupc; then
  $LAUNCH ./indexgupc
else
  $LAUNCH ./indexgather
fi
exit 0
