#!/bin/sh -e

# Copyright (c) 2020, Institute for Defense Analyses
# 4850 Mark Center Drive, Alexandria, VA 22311-1882; 703-845-2500
#
# All rights reserved.
#
# This file is part of the conveyor package. For license information,
# see the LICENSE file in the top level directory of the distribution.

export MPP_INIT_QUIET=1
$LAUNCH ./alltoall? -- <<EOF
-R -A -c160 -w10 -C    simple 100 16
-R -A -c80  -w10 -d -g simple 100
-R -A -c80  -w10 -g -x simple 100
-R -A -c200 -w10 -d -x simple 100 20
-R -A -c240 -w10 -d -p simple 100 24
-R -A -c280 -w10 -p -y simple 100 28
-R -A -c320 -w10 -pxy  simple 100 32
-R -M -c500 -w40       simple 100 64
EOF
exit 0
